### ISSUE TITLE
plannerBucket missing id property

### ISSUE THREAD

**Issue by j0hnsmith** [microsoftgraph/MSGraph-SDK-Code-Generator#118]
`plannerBucket` has an [`id` property](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/plannerbucket#properties), it's not in the metadata (eg https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/25dd44ff9c3f98b80955302e94772f73dc2229de/metadata/v1.0_2017_12_14.xml), can it be added?

**Comment by MIchaelMainer** [comment]
plannerBucket gets its id property from the base entity type.

<EntityType Name="plannerBucket" BaseType="microsoft.graph.entity">
<Property Name="name" Type="Edm.String" Nullable="false" Unicode="false"/>
<Property Name="planId" Type="Edm.String" Unicode="false"/>
<Property Name="orderHint" Type="Edm.String" Unicode="false"/>
<NavigationProperty Name="tasks" Type="Collection(microsoft.graph.plannerTask)"/>
</EntityType>

<EntityType Name="entity" Abstract="true">
<Key>
<PropertyRef Name="id"/>
</Key>
<Property Name="id" Type="Edm.String" Nullable="false" Unicode="false"/>
</EntityType>
