### ISSUE TITLE
Build fails on dev

### ISSUE THREAD

**Issue by PxlBuzzard** [microsoftgraph/MSGraph-SDK-Code-Generator#157]
Building on commit https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/commit/a680c330308a2437df851b16a635375ebb93ef60 results in a build failure:

> src\GraphODataTemplateWriter\Extensions\OdcmModelExtensions.cs(215,27,215,53): error CS1061: 'OdcmSingleton' does not contain a definition for 'NavigationPropertyBindings' and no accessible extension method 'NavigationPropertyBindings' accepting a first argument of type 'OdcmSingleton' could be found (are you missing a using directive or an assembly reference?)

**Comment by MIchaelMainer** [comment]
You probably need to update the vipr submodule. Here's where the support was added: 
https://github.com/Microsoft/Vipr/pull/140/files

**Comment by PxlBuzzard** [comment]
Thank you @MIchaelMainer, that was it. I was updating a few month old copy of this repo and forgot to update the submodules as well.
