### ISSUE TITLE
Support read-only property references

### ISSUE THREAD

**Issue by kevklam** [microsoftgraph/MSGraph-SDK-Code-Generator#17]
The 'directReports' property on user entities is apparently read-only. I don't think OData has a 'native' way of describing a read-only reference property but maybe something can be hacked in the code generator using a custom annotation in the metadata. Though we've been trying to cut down on those types of things.

This should affect all platforms as it's an issue with the metadata description of the service.

**Comment by iambmelt** [comment]
Related: [Data Modification Capabilities](https://github.com/iambmelt/OData-V4.0-Vocabularies#data-modification-capabilities)

**Comment by AndrewJByrne** [comment]
This is still and issue and we don't have a solution in play currently.
