### ISSUE TITLE
Beta version code does not build

### ISSUE THREAD

**Issue by luobingran** [microsoftgraph/MSGraph-SDK-Code-Generator#173]
I am trying to generate beta version code and build it to generate the dlls. The generated code does not build for me. The metadata file I am using beta_2018_09_14_descriptions.xml.
The error I get while try to build
1. it missing some class such as BaseClient.cs HttpProvider.cs Serializer.cs etc
2. After I add all these missing class it complain about AndroidForWorkScepCertificateProfileManagedDeviceCertificateStatesCollectionReferencesRequest did not implement the interface method.

Could you give suggestions which metadata file to use to generate a beta version of code that can build or any steps I am missing.

Thanks a lot.

**Comment by MIchaelMainer** [comment]
We have some work to do to consistently support beta generation. Right now, we have to manually make changes to generate a buildable client. In the meantime, here is a beta client we created in November:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.12.0-beta

**Comment by luobingran** [comment]
Thank you for your response. 
Is there a signed version of these beta version packages?

**Comment by MIchaelMainer** [comment]
We don't have a signed version. We eventually will.

**Comment by luobingran** [comment]
Thanks a lot for your response.
Could I ask any release plan for servicePrincipals related functionality. Will that release in the future few month?
such as GET /servicePrincipals/{id}/appRoleAssignedTo

**Comment by MIchaelMainer** [comment]
I can only speak with confidence on the Microsoft Graph client stories. 

There are dozens of teams that create the service APIs so it is hard to keep up with all of the release plans. I don't know the release plans for that API.

**Comment by MIchaelMainer** [comment]
The client follows the service. When a service API moves from the beta to v1.0 endpoint, the client libraries will *typically* be updated within 1-5 weeks. I can't give an estimate as I don't know when the servicePrincipals functionality hits the v1.0 endpoint.

**Comment by luobingran** [comment]
Thanks a lot for your explanation!
