### ISSUE TITLE
ICollectionRequestBuilder.Base.template.tt needs to inherit from IBaseRequestBuilder.

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#189]
Concrete template CollectionRequestBuilder.Base.template.tt already inherits from BaseRequestBuilder. We should update the interface to reflect this as well. Look at conversation with @ksikorsk for more info. 
[AB#7099](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7099)

**Comment by zengin** [comment]
We don't anticipate more investment into refactoring T4 templates similar to what's been described here.
