### ISSUE TITLE
Update C# *Request and I*Request template to check patch objects on UpdateAsync

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#200]
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/426 
[AB#7103](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7103)

**Comment by zengin** [comment]
C# development moved to kiota.
