### ISSUE TITLE
Add ///<Exception> comments to final *Request.*Async methods

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#201]
This should make it easier for customers to discover that our client throws a ServiceException in response to issues with the service. 
[AB#7104](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7104)

**Comment by baywet** [comment]
Opened an issue to reflect that in kiota. closing
