### ISSUE TITLE
C# EDM containing a type "Task" generates conflicts with "System.Threading.Tasks.Task"

### ISSUE THREAD

**Issue by rifuller** [microsoftgraph/MSGraph-SDK-Code-Generator#21]
Many of the templates generate async code that returns a type Task.  If the EDM also contains an entity with the name "Task", the generated code will be ambiguous and won't compile.

**Comment by kevklam** [comment]
I think there's a reserved words list you can add it to

**Comment by richard-fuller** [comment]
It's actually already exists in the reserved names list.  Haven't debugged beyond that.

https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/master/src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs

**Comment by ginach** [comment]
It's probably not calling the extension method to clean the name during gen.

**Comment by ginach** [comment]
You'll also probably want a better prefix if we're actually going to use it. We should really be avoiding using common reserved words like that in the service if we can avoid it. With prefixing it affects discoverability of the request builders. client.Thing.MSTask or whatever doesn't intuitively point to /thing/task. My $.02.

**Comment by shiftylogic** [comment]
I changed the sanitize function(s) to use the @ prefix in C# which escapes conflicting keywords. To solve the Task conflict, we should just fully qualify the Task return type in generated code.
