### ISSUE TITLE
.Search(query) helper is missing from collections

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/MSGraph-SDK-Code-Generator#214]
Following on from [Issue 178](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/178) in the SDK.

Unlike the [JavaScript API](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/QueryParameters.md) the `.Search` query parameter helper is missing in the C# SDK.

It'd be nice to have a helper for this to make porting code samples between the two languages easier and more consistent. 
[AB#6238](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6238)

**Comment by zengin** [comment]
fixed in kiota. See linked issue from the original issue description for more details
