### ISSUE TITLE
Does this generate a javascript/typescript library to call all the MSGraph API?

### ISSUE THREAD

**Issue by chauey** [microsoftgraph/MSGraph-SDK-Code-Generator#22]
I can't quite understand what this does. Does this generate a javascript/typescript library to call all the MSGraph API? What (else) is out there currently that can help have some Typescript library to call all the MSGraph beta API? thx

**Comment by cdmayer** [comment]
This simply helps you generate code based on published OData metadata. It helps you to work with anything provided by an OData resource without manually writing a corresponding class for every Entity or Complex Type. 

A more concrete example: a version of this was used to generate the [OneDrive Python SDK](https://github.com/OneDrive/onedrive-sdk-python) based on the [OneDrive metadata](https://api.onedrive.com/v1.0/$metadata). If you take a look at the [Models](https://github.com/OneDrive/onedrive-sdk-python/tree/master/src/onedrivesdk/model), you can see that every EntityType in the metadata doc has a corresponding Python class. We didn't write all that by hand - we wrote an EntityType template, then pointed this tool at the metadata doc. The output is the files you see there.

There currently are no TypeScript templates. However, using the templates in the repository as a guide, one could write the appropriate TypeScript templates to generate the whatever is needed. I hope that answers your questions!

**Comment by chauey** [comment]
I see, so it creates just the entities. Thanks for the reply!

Is there a way to deserialize the metadata into EntityFramework or something, and then create a SQL Server DB from it?

Or any way to get swagger/OAI doc from/for the Microsoft graph?

Also curious if you know how to get TypeScript/javascript client library to call the Microsoft graph API?

Thanks! This all seems related to MSGraph SDK. :)
