### ISSUE TITLE
MethodRequestBuilder.cs.tt - fix warning for missing XML comment

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#225]
Parameters named with the name of a c# keyword are prepended with `@` to both the parameter name in the cstor and the XML comments. It shouldn't be in the XML comments. This only affects 2 parameters throwing off 4 compile warnings. 

Affects WorkbookFunctionsLogRequestBuilder and WorkbookFunctionsRank_AvgRequestBuilder 
[AB#7107](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7107)

**Comment by zengin** [comment]
C# development moved to kiota
