### ISSUE TITLE
Add Request methods that take a body but don't actually make the call

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/MSGraph-SDK-Code-Generator#229]
In order to support creating Batch requests that contain request bodies, we need to be able to have methods that set the HTTP method and content, without actually making the HTTP call.
e.g.  when a request has a PostAsync(body) method, it should also have a AsPost(body) that returns the Request object.
I'm open to discuss the new method naming.
[AB#6084](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6084)

**Comment by maisarissi** [comment]
This was addressed in Kiota.

**Comment by andrueastman** [comment]
> This was addressed in Kiota.

This is through the `CreateXXXXRequestInformation` methods available in the request builders

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#use-of-requestinformation-from-kiota-in-place-of-ibaserequest
