### ISSUE TITLE
Move all pipelines off of local build agent

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#230]
Everything under Generation and .NET need to moved off of the Microsoft Graph agent running on the local machine. typewriter.exe updates should now result in a a release where typewriter can be downloaded as an [asset](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/releases). 

Everything under .NET and Generation pipelines need to be updated to use the Azure hosted agents. 

Downloading typewriter.exe:

1) https://api.github.com/repos/microsoftgraph/MSGraph-SDK-Code-Generator/releases
2) Get the first object.
3) if item[0].assets[0].name == tuypewriter.exe, download at browser_download_url 
[AB#7108](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7108)

**Comment by zengin** [comment]
This is a stale issue, closing...
