### ISSUE TITLE
DerivedTypeConverter incorrectly applied

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#237]
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/Templates/CSharp/Model/ComplexType.cs.tt#L44

```csharp
if (complex.Derived != null && complex.Base == null)
{
    attributeStringBuilder.Append(Environment.NewLine);
    attributeStringBuilder.Append("    ");
    attributeStringBuilder.Append("[JsonConverter(typeof(DerivedTypeConverter))]");
}
```

**complex.Derived** is never null as far as I've observed. It can be an empty list. We should change this check to `complex.Derived?.Count > 0` 
[AB#7081](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7081)

**Comment by zengin** [comment]
C# generation moved to kiota
