### ISSUE TITLE
IGraphServiceClient is not necessary

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#241]
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/IGraphServiceClient.cs

Search on the use of this. It isn't necessary. 
[AB#7082](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7082)

**Comment by andrueastman** [comment]
This was dropped in V4 of the .NET SDK.
