### ISSUE TITLE
Remove scenarios where we set odata.type by default for C#

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#242]
Only add Odata.type when working with derived types and heterogenous collections.

I think this issue is a duplicate 
[AB#7083](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7083)

**Comment by andrueastman** [comment]
Closed via #534
