### ISSUE TITLE
New-MgUser fails 'does not exist or one of its queried reference-property objects are not present.'

### ISSUE THREAD

**Issue by ThePoShWolf** [microsoftgraph/MSGraph-SDK-Code-Generator#244]
When creating a new user with ```New-MgUser```, if not all of the required parameters are passed it throws a rather cryptic error:

```text
Resource 'User_<guid>' does not exist or one of its queried reference-property objects are not present.
```

I found that this happened because I wasn't passing a ```MailNickname``` parameter. After also passing that parameter, it created the user as expected.

For anyone else that runs into this, here are the [required parameters](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http).

It would be great if the module returned a better error or had required parameters so it was clear in the cmdlet's help. I'm sure this has or will come up in other cmdlets. 
[AB#7085](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7085)

**Comment by peombwa** [comment]
This is an old service issue that can be closed. The API will now fail with the correct error message, indicating which property is missing. In this case, `Property mailNickname value is required but is empty or missing.`

The missing requiredProperties annotations mentioned by Michael is currently being tracked at https://github.com/microsoftgraph/msgraph-metadata/issues/278.
