### ISSUE TITLE
ObjectIdentity is not present in the extension model for User object in Java

### ISSUE THREAD

**Issue by nagygm** [microsoftgraph/MSGraph-SDK-Code-Generator#246]
In the 1.7.1 version of the Java artifact sdk, there is no ObjectIdentity list property for the User class. So the example of how to add identites for a user is invalid: 
https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=java#request-1

**Comment by ddyett** [comment]
i do see see this in .NET but not in Java so it looks like a bug in generation.  As part of working on getting a new version out will see if we can fix this.

**Comment by MIchaelMainer** [comment]
Work started

**Comment by baywet** [comment]
@nagygm Thanks for letting us know, this had been added for version 1.8.0 and up https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/models/extensions/User.java#L237
Closing
