### ISSUE TITLE
CallRecords missing in the SDK (3.7.0)?

### ISSUE THREAD

**Issue by roygarbriceno** [microsoftgraph/MSGraph-SDK-Code-Generator#248]
**Describe the bug**
CallRecords is GA, and according to the documentation, I should be able to do something as simple as:

GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var callRecord = await graphClient.Communications.CallRecords["{id}"]
	.Request()
	.Expand("sessions($expand=segments)")
	.GetAsync();

(https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0&tabs=csharp)

However hasta installing the latest version of the SDK (3.7.0, updated 2 days ago) I dont find "CallRecords", only "Calls" and "OnlineMeetings". 

¿Is CallRecords on a different package?, would be added later?

**To Reproduce**
1. Create a sample  C# project 
2. Add the Microsoft.Graph nuget package (latest, 3.7.0 at this moment)
3. Add the above sample line
4. Try to build

**Expected behavior**
The sample should build with the code provided on the documentation

Linked to [AB#4590](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4590)

**Comment by sbriley1979** [comment]
Any further news on this? I installed 3.8 this morning and I've encountered the same issue.

**Comment by ddyett** [comment]
there's no date for this yet but we've started working on it and it's likely to appear in the dotnet versions first.

**Comment by zengin** [comment]
This is available as of Microsoft.Graph nuget package version 3.12.0.
