### ISSUE TITLE
User RevokeSignInSessions does not handle proper response type

### ISSUE THREAD

**Issue by kensykora** [microsoftgraph/MSGraph-SDK-Code-Generator#249]
**Describe the bug**
I'm trying to invoke this endpoint here: https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http

It describes it as 

```
POST /users/{id | userPrincipalName}/revokeSignInSessions
```

I'm invoking the c# client lib as such:

```csharp
public async Task RevokeSignInSessions(Guid id)
        {
            await _graphClient.Users[id.ToString()]
                .RevokeSignInSessions()
                .Request()
                .PostAsync();
        }
```

However, this throws an error:

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.DeserializeObject[T](String inputString)
   at Microsoft.Graph.ResponseHandler.HandleResponse[T](HttpResponseMessage response)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at UserManagement.Core.Concretes.AdGraphService.RevokeSignInSessions(Guid id)
```

**To Reproduce**
1. Run code snippet as described above

*Expected*: Task continues without error if the operation is successful.
*Actual*: Refresh tokens are revoked, but SDK throws the above exception.

**Screenshots**

**Additional context**
NuGet version 

Microsoft.Graph v3.6.0
Microsoft.Graph.Auth v1.0.0-preview.4

 
[AB#7087](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7087)

**Comment by twentytwokhz** [comment]
Any updates on this?

**Comment by zengin** [comment]
This is what the body of successful HTTP response (200) looks like:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Edm.Null",
    "@odata.null": true
}
```

I don't think the response is consistent with the `boolean` return type from the metadata either.

I think we should consider this as a service issue. @MIchaelMainer, do you agree?

**Comment by MIchaelMainer** [comment]
I can't find anything in the [OData docs](https://www.odata.org/documentation/) about how to represent a primitive in a method response body. Certainly nothing specific in the action documentation. Let's see if we can find an answer about what we should expect here.

**Comment by zengin** [comment]
Quoting from http://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_IndividualPropertyorOperationRespons

> A property or operation response that is of a primitive type is represented as an object with a single name/value pair, whose name is value and whose value is a primitive value.

I think the response should be:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Edm.Boolean",
    "value": true
}
```

Example function where the response type is `string`:
https://docs.microsoft.com/en-us/graph/api/intune-devices-applepushnotificationcertificate-downloadapplepushnotificationcertificatesigningrequest?view=graph-rest-1.0

**Comment by MIchaelMainer** [comment]
@zengin Nice find!

**Comment by zengin** [comment]
Service team is engaged to fix the response.

**Comment by hcoberdalhoff** [comment]
oookay.... This is still ongoing / this endpoint is still not usable, right?

Just tried it:

A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) \u0027Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType,
Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType,
Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType,
Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType,
Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType,
Microsoft.OData.ODataMediaTyp...\u0027 matches the content type \u0027application/x-www-form-urlencoded\u0027.",
                  "innerError":  {
                                     "date":  "2021-12-06T13:21:00",
                                     "request-id":  "8c072000-e1d2-4280-be92-fe17c3825fe7",
                                     "client-request-id":  "8c072000-e1d2-4280-be92-fe17c3825fe7"
                                 }
