### ISSUE TITLE
Add/Remove methods are not implemented on collections

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/MSGraph-SDK-Code-Generator#250]
Metadata has `add` and `remove` actions defined on a collection of microsoft.graph.site. It looks like we don't support generating methods for actions defined on collections.

```
<Action Name="add" IsBound="true">
<Parameter Name="bindingParameter" Type="Collection(graph.site)"/>
<Parameter Name="value" Type="Collection(graph.site)"/>
<ReturnType Type="Collection(graph.site)"/>
</Action>

<Action Name="remove" IsBound="true">
<Parameter Name="bindingParameter" Type="Collection(graph.site)"/>
<Parameter Name="value" Type="Collection(graph.site)"/>
<ReturnType Type="Collection(graph.site)"/>
</Action>
```

Example Requests:
https://docs.microsoft.com/en-us/graph/api/site-follow?view=graph-rest-1.0&tabs=csharp#request
https://docs.microsoft.com/en-us/graph/api/site-unfollow?view=graph-rest-1.0&tabs=csharp#request 
[AB#7086](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7086)

**Comment by MIchaelMainer** [comment]
This needs to be supported on non-contained entities.
  ` <NavigationProperty Name="followedSites" Type="Collection(graph.site)" />`

**Comment by MIchaelMainer** [comment]
More specifically, we don't support generating methods for actions defined on **reference** collections. It is generated for 
`await client.Sites[""].Sites.Add(new List<Site>()).Request().PostAsync()`

      <EntityType Name="user" BaseType="graph.directoryObject" OpenType="true">
        <NavigationProperty Name="followedSites" Type="Collection(graph.site)" />
      </EntityType>

**Comment by darrelmiller** [comment]
We need to figure out someway to identify whether these methods are actually implemented by the service on the reference collections.

**Comment by zengin** [comment]
@darrelmiller I confirmed that `remove` works even though it throws 207 with a general exception. A subsequent `GET` query returned a set which doesn't contain the removed item.

`add` also works properly with a `200`.

We already have a way of adding references but it requires one call per reference whereas these `add/remove` actions allow multiple references in a single call.

**Comment by baywet** [comment]
double checking we're not missing something in Java at this moment:
- only 1 remove method present for sites
- 6 add methods present for Excel things and 1 for sites

Should there be more?

**Comment by zengin** [comment]
@baywet, please refer to the example requests mentioned in the initial issue description for scope. If add/remove for followed sites in Java is working similar to the HTTP sample, we should be good.

**Comment by baywet** [comment]
thanks, it looks to be on part. I also looked at the metadata and the numbers match what I was sharing. Removing the java tag.

**Comment by baywet** [comment]
reviewing from the kiota checklist: [kiota solves that issue for us](https://github.com/microsoftgraph/msgraph-sdk-go/blob/63d146b9a9e6c9f8dce806eb2a5cafdc4e0e392a/sites/add/add_request_builder.go#L77)
