### ISSUE TITLE
Java: refactor UpdateListPropertiesWithinSetRawObject to remove duplicate code

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#259]
Sure would like to have Span<T> for this.

https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/Templates/Java/BaseJavaModel.template.tt#L1168

We are duplicating the same code with only changes to strings. 
[AB#7088](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7088)

**Comment by baywet** [comment]
closing since we're moving to kiota and won't be investing in cleaning the code for this generator
