### ISSUE TITLE
Is the generated c# code supposed to compile? or just get us some starter code?

### ISSUE THREAD

**Issue by chauey** [microsoftgraph/MSGraph-SDK-Code-Generator#26]
Hello all,

i generated the C# code, put it into a c# web api project, but got many errors.

Errors with DerivedTypeConverter, EnumConverter, syntax, etc.

And it takes a long time to include/build/collect-errors.. any advice and tips what we should see and how to use, what's undone and todo for it to be usable, etc.
 thx

**Comment by MIchaelMainer** [comment]
Hello @chauey,

I think you'll want to use the [MS Graph .Net Client SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet). You can install the client API from Nuget `Install-Package Microsoft.Graph`.

Here's a set of samples that may help:
https://github.com/microsoftgraph?utf8=%E2%9C%93&query=aspnet

Have a good one.
