### ISSUE TITLE
feature: support odata cast derivedconstraint for .NET

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#304]
similar to work done for https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/303 
[AB#6325](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6325)

**Comment by zengin** [comment]
stale issue
