### ISSUE TITLE
feature: add composable function support for composed methods in Java

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#315]
Composable function support needs to include request builders for both navigation properties and methods. PR 291 includes support for navigating from the results of a composable function. We need to add support for methods on the the results of the composable function.

https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/291/files

Scenario:
https://graph.microsoft.com/v1.0/me/drive/items/01DVF26FC76CZBQT2BIVD3XCX2MLZRGDIP/workbook/worksheets/Sheet1/microsoft.graph.range()/microsoft.graph.lastcolumn() 
[AB#7092](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7092)

**Comment by ddyett** [comment]
addressed in V6 version of the SDK
