### ISSUE TITLE
Support deprecation for PHP

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#342]
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/283 
[AB#6807](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6807)

**Comment by baywet** [comment]
Closing since this is now tracked in this issue. https://github.com/microsoft/kiota/issues/2799
