### ISSUE TITLE
Support deprecation for C# on all request builders

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#356]
IMethodRequest, *StreamRequest, *EntityWithReferenceRequeest, *EntityRequest, *EntityReferenceRequest, *EntityCollectionWithReferencesRequest, *EntityCollectionRequest, *EntityCollectionReferencesRequest, MethodRequestBody. 
[AB#6862](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6862)

**Comment by MIchaelMainer** [comment]
We also need spec from @mikepizzo about how the deprecation statements should be propagated by tools. 

A non-exhaustive list of questions and assumptions:
- Where can deprecation annotations exist in the CSDL?
- If derived type is deprecated and the base type is referenced, how do we handle references to the base type? Is it conditionally deprecated?
- If a property is deprecated on a complex type or entity, does that mean all references to the complex type or entity are deprecated?
- If a type is deprecated, all methods bound to the type, or that contains a parameter of that type, or that returns that type (or collections thereof) are deprecated.
- Base type deprecation - all derived types are deprecated as well as their bound methods, even if the derived type is not explicitly marked as deprecated.

This list could go on.... we need an OData spec on this.

**Comment by baywet** [comment]
closing since this has been addressed in kiota
