### ISSUE TITLE
TemplateWriterSettings.json takes a dependency on source

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/MSGraph-SDK-Code-Generator#374]
```json
{
  "TemplatesDirectory": "../../../../../Templates"
}
```

The setting above uses a path from bin directory to the source directory, so using just the bin directory as an executable doesn't work.

We should instead have a step in our build to copy all Templates into the bin folder and have a relative path within bin directory for the templates.

cc: @baywet @MIchaelMainer

**Comment by baywet** [comment]
I was struggling with that a while ago, and I changed the templates to "copy of newer". Si they should already be copied by now.
I think all what's left should be to update the path management and maybe remove this setting all together.

**Comment by zengin** [comment]
@baywet these are not copied to bin folder at all. Even the csproj file was referencing only to the subset of files. Both the test project and the actual Typewriter project were picking up from the source folder (dotnet core changes needed one more ../ because the new bin path has one more layer of directories, namely net5.0)

Anyways, my linked PR closes this issue as well.

**Comment by baywet** [comment]
hum, ok, thanks for fixing that! I thought I had done it but my unreliable memory must be confusing with some other kind of file we depend on...
