### ISSUE TITLE
Add support for SupportedFormats capability annotation.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/MSGraph-SDK-Code-Generator#398]
The SupportedFormats annotation indicates which media types are supported for an entity container.  The presence of this annotation should cause SDKs to support adding a format query parameter to a request.

https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml#L135

This feature is used by DriveItem and a many of our reports.
https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http 
[AB#7603](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7603)

**Comment by baywet** [comment]
closing since this is now supported by the conversion library https://github.com/microsoft/OpenAPI.NET.OData/blob/6272df950c515e4681e93994a38299c65d6013b6/test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/EdmVocabularyAnnotationExtensionsTests.cs#L125
