### ISSUE TITLE
Remove TemplateMapping - Shared

### ISSUE THREAD

**Issue by peternied** [microsoftgraph/MSGraph-SDK-Code-Generator#4]
The [shared [...]](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/master/src/GraphODataTemplateWriter/.config/TemplateWriterSettings.json#L17) settings for the templates concept has outlived its usefulness.  Each template should instead have all of its sub processor mappings in the single language file since they have diverged so much over the evolution of this project.
 
[AB#7096](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7096)

**Comment by MIchaelMainer** [comment]
2123604
