### ISSUE TITLE
Create RequestBuilders for structural properties that need to be accessed directly

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/MSGraph-SDK-Code-Generator#400]
e.g.  mailboxsettings

and 

https://graph.microsoft.com/beta/print/printers/{id}/jobs/{id}/configuration

Currently we don't know when this is possible and instead of generating RequestBuilders for every structural property we don't generate any.  We should use a capability annotation to indicate that support is required. 
[AB#7626](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7626)

**Comment by MIchaelMainer** [comment]
Would we want to support accessing arbitrary structural properties as the API supports this? I can't think of any reason since we can select. 

For example, I can do the following:

```http
GET https://graph.microsoft.com/v1.0/me/jobtitle
```


```http
PATCH https://graph.microsoft.com/v1.0/me/jobtitle

{
  "value":"Marketing Director2"
}
```

Instead of doing:

```http
GET https://graph.microsoft.com/v1.0/me?$select=jobtitle
```

```http
PATCH https://graph.microsoft.com/v1.0/me/jobtitle

{
  "jobTitle":"Marketing Director3"
}
```

We could enable scenarios like these for .NET:

```csharp
// Get the type parameter when the property is selected.
client.Me.GetProperty(u => u.MailboxSettings).Request().GetAsync<MailboxSettings>();
// Don't need to new up an object to update a single property.
client.Me.SetProperty(u => u.JobTitle, "Marketing Director2").Request().UpdateAsync();
```

**Comment by baywet** [comment]
closing since this is now supported by the conversion library and kiota https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/e3d59b67608b7496804ff007f2b2da59ce22bd2e/src/Microsoft.Graph/Generated/Users/Item/MailboxSettings/MailboxSettingsRequestBuilder.cs#L12
