### ISSUE TITLE
Add support for CountSegment

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/MSGraph-SDK-Code-Generator#402]
The [CountSegment ](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingtheCountofaCollection) isn't catered for requestBuilders in the SDK 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/875

[AB#7634](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7634)

**Comment by baywet** [comment]
reviewing from the Kiota checklist: it should, however [there seems to be an issue with the OData to OpenAPI conversion process](https://github.com/microsoft/OpenAPI.NET.OData/issues/129)
