### ISSUE TITLE
Add a rule for docs validation to prevent curly apostrophe

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/MSGraph-SDK-Code-Generator#424]
See https://github.com/microsoftgraph/microsoft-graph-docs/pull/11538 for an example fix of this problem.

This causes our generated code comments to look weird. 
[AB#8011](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8011)

**Comment by baywet** [comment]
closing since the code comments clean up in now done in kiota.
