### ISSUE TITLE
Add support for bulk update

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/MSGraph-SDK-Code-Generator#440]
Work to be done:
- Identify when PATCH can be performed on a collection based on capability annotations
- Verify that collection classes can be constructed with the appropriate annotations for adding/updating and deleting
- Ensure proper handling of responses containing partial failures.

OData specification  https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_UpdateaCollectionofEntities  
[AB#8133](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8133)

**Comment by zengin** [comment]
Related: https://github.com/microsoft/kiota/issues/63
