### ISSUE TITLE
Add constructor to GraphServiceClient to accept an object derived from TokenCredential

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/MSGraph-SDK-Code-Generator#461]
This avoids the user having to instantiate their own instance of TokenCredentialAuthProvider 
[AB#8218](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8218)

**Comment by andrueastman** [comment]
Closed via #477
