### ISSUE TITLE
Investigate inconsistent failure of .NET PR check

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/MSGraph-SDK-Code-Generator#490]
The failure is as follows -
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/488/checks?check_run_id=2125318477
On retriggering, this check didn't report the same failure and passed successfully. 

 
[AB#8623](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8623)

**Comment by andrueastman** [comment]
Closing this one for now unless the issue re-occurs. Most of the generation code in the repo is now removed/deprecated. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1269
