### ISSUE TITLE
Consider adding a compilation test for the test data

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/MSGraph-SDK-Code-Generator#494]
Test data is currently reviewed manually, but it is possible to miss edge cases. See an example in #493

This can be achieved by checking out the corresponding sdk repo (e.g. msgraph-sdk-dotnet), copying models from the TestData folders (e.g. TestDataCSharp) and compiling the sdk solution. 
[AB#8626](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8626)

**Comment by baywet** [comment]
closing since the generation of most languages has already moved to Kiota and Kiota has integration tests to do just that.
