### ISSUE TITLE
Set correct return type in PHP Docs for types that clash with PHP keywords

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/MSGraph-SDK-Code-Generator#521]
GraphList is a model whose name is derived by pre-pending "Graph" to the actual EntityType `List` in the metadata in order to prevent clashing with keywords in PHP.

The phpDocs generated however still show return type as `List` instead of `GraphList` e.g.

```php
  /**
  * Sets the list
  * Provides additional details about the list.
  *
  * @param ListInfo $val The list
  *
  * @return List
  */
  public function setList($val)
  {
      $this->_propDict["list"] = $val;
      return $this;
  }
``` 
[AB#9134](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9134)

**Comment by guilliamxavier** [comment]
Maybe simpler `@return $this`? more accurate and understood by most IDEs/tools
