### ISSUE TITLE
PHP Generation DateTime::RFC3339 is removed

### ISSUE THREAD

**Issue by tolbon** [microsoftgraph/MSGraph-SDK-Code-Generator#523]
Hello team,

I run PHPStorm InspectCode on msgraph-sdk-php  
for example src/Beta/Microsoft/Graph/Model/AppCatalog.php line 117

> 'RFC3339' was removed in 7.2 PHP version

reveal that on 17 files other Model file.
[PHP Docs](https://www.php.net/manual/en/class.datetime.php#datetime.changelog) says same things. 

The fix is replace `DateTime::RFC3339` by `DateTimeInterface::RFC3339` 
[AB#9200](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9200)

**Comment by SilasKenneth** [comment]
Hello @tolbon, thanks for raising this. Will be working on a fix ASAP.

**Comment by SilasKenneth** [comment]
Though the according to the [DateTime documentation](https://www.php.net/manual/en/class.datetime.php), the `DateTime` implements the `DateTimeInterface` and the constants in the DateTimeInterface are available in `DateTime`.

**Comment by baywet** [comment]
closing since this was resolved with #541
