### ISSUE TITLE
msgraph-sdk-go?

### ISSUE THREAD

**Issue by liamjbennett** [microsoftgraph/MSGraph-SDK-Code-Generator#53]
Would it be possible to generate a golang sdk? It would make a great compliment to the existing azure sdk for go.

**Comment by cdmayer** [comment]
Certainly it would be possible! You would need to write a set of templates analogous to those available in the other languages, and you would need to write the 'core' library (such as HttpProvider, AuthenticationProvider, etc.). Let me know if you want more details on how to get it done. If you do write such a set of templates, be sure to publish a Pull Request!
