### ISSUE TITLE
Name `Microsoft.Graph.Security` Collision Between Namespace and Class FQN

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/MSGraph-SDK-Code-Generator#666]
Issue detected in pipeline [run here](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=65200&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa).

Error: error CS0101: The namespace 'Microsoft.Graph' already contains a definition for 'Security'

Need to refactor the generator to make it possible for the namespace and class to co-exist without raising compilation error.

Workload owner Confirmed the intentionality of the above as follows:
"
    `The microsoft.graph.security` singleton in Prod (beta & v1.0) exists for few years. It does not exists in PPE. I added it to my workload in PPE in order to mimic the same behavior as in Prod. We've been requested to move all our entities (in M365Defender workload) to a new sub namespace - `microsoft.graph.security`. We moved all our entities to the new sub namespace, but we didn't touch the security singleton in order to mimic the behavior in Prod
"

**Comment by MIchaelMainer** [comment]
@fey101 Is it the same functionality in the m.g.security entity as in the m.g.security namespace?

**Comment by andrueastman** [comment]
> @fey101 Is it the same functionality in the m.g.security entity as in the m.g.security namespace?

@MIchaelMainer I believe that would be correct. It seems that the existing entity (m.g.security) is being enriched with property types from the new m.g.security namespace according to the staging metadata.

![image](https://user-images.githubusercontent.com/6464005/152105427-31e54be3-ab25-48b9-9533-e08a6b5af551.png)
