### ISSUE TITLE
ItemWithPath not appending an item path for NextPageRequest

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#71]
This calls contains the correct URL structure:
```
var path = "Community Service";
var driveItemsPage = await graphClient.Me.Drive.Root.ItemWithPath(path).Children.Request().Top(1).GetAsync(); 
// https://graph.microsoft.com/v1.0/me/drive/root:/Community%20Service:/children?$top=1
```

This call does not issue the correct URL. Notice that ":/Community%20Service:" segment is missing.
```
driveItemsPage = await driveItemsPage.NextPageRequest.GetAsync();
// Actual
// https://graph.microsoft.com/v1.0/me/drive/root/children?$top=1&$skiptoken=Paged%3dTRUE%26p_SortBehavior%3d0%26p_FileRef%3dpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service%252fBook%252exlsx%26p_ID%3d390%26RootFolder%3d%252fpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service
// Expected
// https://graph.microsoft.com/v1.0/me/drive/root:/Community%20Service:/children?$top=1&$skiptoken=Paged%3dTRUE%26p_SortBehavior%3d0%26p_FileRef%3dpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service%252fBook%252exlsx%26p_ID%3d390%26RootFolder%3d%252fpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service
```
This call does issue the correct URL: 
```
driveItemsPage = await graphClient.Me.Drive.Root.ItemWithPath(path).Children
                              .Request(driveItemsPage.NextPageRequest.QueryOptions)
                              .GetAsync();
```

If we don't use the root segment, and use the items collection, the NextPageRequest works as expected.
 
```
                var driveItemsPage = await graphClient.Me.Drive.Items["015U5LKCS34Q6NKSEKZVDZMNVKDTXJ4CUR"].Children.Request().Top(1).GetAsync();
                driveItems.AddRange(driveItemsPage.CurrentPage);

                while (driveItemsPage.NextPageRequest != null)
                {
                    driveItemsPage = await driveItemsPage.NextPageRequest.GetAsync();
                    driveItems.AddRange(driveItemsPage.CurrentPage);
                }
```

Reported in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/54.

**Comment by iambmelt** [comment]
@MIchaelMainer impacts other platforms too?

**Comment by MIchaelMainer** [comment]
This has potential impact on other platforms. It is worth investigating although do note that there are alternate work flows for the same result.

**Comment by MIchaelMainer** [comment]
This is an issue with the service returning a bad next link in the ItemWithPath scenario. 

**Request**
GET /v1.0/me/drive/root:/Community%20Service:/children?$top=1

**Response nextLink**
// Actual nextLink value used to populate the NextPageRequest URL
`https://graph.microsoft.com/v1.0/me/drive/root/children?$top=1&$skiptoken=Paged%3dTRUE%26p_SortBehavior%3d0%26p_FileRef%3dpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service%252fBook%252exlsx%26p_ID%3d390%26RootFolder%3d%252fpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service
`                
// Expected nextLink value used to populate the NextPageRequest URL
`https://graph.microsoft.com/v1.0/me/drive/root:/Community%20Service:/children?$top=1&$skiptoken=Paged%3dTRUE%26p_SortBehavior%3d0%26p_FileRef%3dpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service%252fBook%252exlsx%26p_ID%3d390%26RootFolder%3d%252fpersonal%252fgarthf%255fmod810997%255fonmicrosoft%255fcom%252fDocuments%252fCommunity%2520Service
`
