### ISSUE TITLE
Beta generation fails due to transform adding a removed/non-existent type

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/MSGraph-SDK-Code-Generator#727]
At the moment it looks like beta generation is failing due to typewriter unable to resolve the type `crossTenantAccessPolicyConfigurationBase` in the metadata.

Looking at the public metadata [here](https://graph.microsoft.com/beta/$metadata) the type looks to have been cleanly removed.

However, after the transform is run with typewriter it looks like the `crossTenantAccessPolicyConfigurationPartner` type which originally had no base in the public metadata is given the nonexistent base(`crossTenantAccessPolicyConfigurationBase`) after transform.

Before Transform from public metadata. (Entity has no base though. It looks like it was removed)
```xml
      <EntityType Name="crossTenantAccessPolicyConfigurationPartner">
        <Key>
          <PropertyRef Name="tenantId" />
        </Key>
        <Property Name="b2bCollaborationInbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="b2bCollaborationOutbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="b2bDirectConnectInbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="b2bDirectConnectOutbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="inboundTrust" Type="graph.crossTenantAccessPolicyInboundTrust" />
        <Property Name="isServiceProvider" Type="Edm.Boolean" />
        <Property Name="tenantId" Type="Edm.String" Nullable="false" />
      </EntityType>
```

After transform 
```xml
      <EntityType Name="crossTenantAccessPolicyConfigurationPartner" BaseType="microsoft.graph.crossTenantAccessPolicyConfigurationBase">
        <Property Name="b2bCollaborationInbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="b2bCollaborationOutbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="b2bDirectConnectInbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="b2bDirectConnectOutbound" Type="graph.crossTenantAccessPolicyB2BSetting" />
        <Property Name="inboundTrust" Type="graph.crossTenantAccessPolicyInboundTrust" />
        <Property Name="isServiceProvider" Type="Edm.Boolean">
          <Annotation Term="Org.OData.Core.V1.Description" String="Identifies whether the partner-specific configuration is a Cloud Service Provider for your organization." />
        </Property>
        <Property Name="tenantId" Type="Edm.String" Nullable="false">
          <Annotation Term="Org.OData.Core.V1.Description" String="The tenant identifier for the partner Azure AD organization. Read-only. Key." />
        </Property>
        <Key>
          <PropertyRef Name="tenantId" />
        </Key>
      </EntityType>
```

There's the possibility this is being pulled from the docs as it still shows the type being derived from `crossTenantAccessPolicyConfigurationBase`

cc @zengin @MIchaelMainer 

Generation run : -
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=73348&view=logs&j=75842713-d241-5c51-b0b4-a337631cec97&t=93e7aeb6-793f-5af5-c48e-adfe7d043cbf

**Comment by zengin** [comment]
sounds like the docs will need to remove the base type too.

**Comment by andrueastman** [comment]
Closing this for now. Looks like the docs have now been updated via https://github.com/microsoftgraph/microsoft-graph-docs/pull/16340

Generation will be rerun with the latest docs update.
